# run: conda env create --file environment.yml

name: tumieszkaj-crawler
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - jupyterlab
  - pip
  - matplotlib
  - shapely
  - pip:
      - anytree
      - tables
      - scrapy
      - geopy
      - OSMPythonTools
      - overpy
      - gtfstk
